config/routes.rb
Rails.application.routes.draw do
    resources:tweets
    root 'tweets#index'
    
      # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :message,presence:true,length:{maximum:140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    
    def index
        @tweets = Tweet.all
    end
    
    def new
        @tweet = Tweet.new
        
    end
    
    def create
        @tweet = Tweet.new(message: params[:tweet][:message],tdate: Time.current)
        if @tweet.save
            redirect_to '/'
        else
            render 'new'
        end
    end
    
    def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to '/'
    end
    
    def show
        @tweet = Tweet.find(params[:id])
    end
    
    def edit
        @tweet = Tweet.find(params[:id])
    end
    
    def update
        tweet = Tweet.find(params[:id])
        tweet.update(message: params[:tweet][:message])
        redirect_to '/'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_header.html.erb
<header>
    <h1>twitterもどき</h1>
</header>

app/views/layouts/_sidebar.html.erb
<h2>
    近畿大学
</h2>
<p>
    @kinkidaigakuPR
</p><br>

<p>
    近畿大学のTwitter公式アカウントです。気象警報による休講情報や、お得なランチ情報など、大学に関する情報を発信します。マグロに関するツイート多め🐟学生のみなさんの相談に乗りますので、くだらないことも気軽に話しかけてください。履修に関するご質問は所属学部。入試に関するご相談は、入学センターへお問い合わせ下さい。
</p>

<p><%= link_to 'ツイート',new_tweet_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div class="container">
	  <div class="header">
		  <%= render 'layouts/header' %>
	  </div>

	  <div class="sidebar">
    <%= render 'layouts/sidebar' %>
    </div>
  
	  <div class="content">
      <%= render 'layouts/content' %>
        <%= yield %>
	  </div>

	  <div class="footer">


	  </div>
	</div>
  </body>
</html>

app/views/tweets/edit.html.erb
<%= form_for @tweet ,url:{action: :update} do |f| %>
    <%= f.label :message,'メッセージ' %>
    <%= f.text_field :message %><br>
    <%= f.submit '更新' %>
<% end %>

app/views/tweets/index.html.erb
<p><%= link_to 'ツイート',new_tweet_path %></p><hr>
<% @tweets.each do |tweet| %>
    <p>
        <%= tweet.message %>
    </p>
    <p align="right">
        <%= link_to  '削除',tweet_path(tweet.id),method: :delete %>
        <%= link_to  '編集',edit_tweet_path(tweet.id) %>
        <% time = (Time.current-tweet.tdate).to_i %>
        <% if time > 3600*24 %>
            <% day = time/3600/24  %>
            <%= day %>日前
        <% elsif time > 3600 %>
            <% hour = time/3600  %>
            <%= hour %>時間前
        <% elsif time > 60 %>
            <% min = time/60  %>
            <%= min %>分前
        <% else %>
        <%= time %>秒前<br>
        <% end %>
        <hr>
    </p>
<% end %>

app/views/tweets/new.html.erb
<%= render 'layouts/content' %>
<%= form_for @tweet ,url:{action: :create} do |f| %>
    <%= f.label :message,'メッセージ' %><br>
    <%= f.text_area :message, :size=>"60x10"%><br>

    <%= f.submit 'ツイート' %>
<% end %>